### ISSUE TITLE
Review process and initial plan

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/auth#1]
Hi, thanks again for setting this repo up - really appreciate it! :) I've got a fair bit of boilerplate code to push up so we should have everything required straight away and I have also made a start on the core functionality. Before I commit anything to the repo, I just wanted to double check what your preference is regarding the commit + review process for a pre-release repo like this?

Here's my initial plan in chronological order to get the first release ready:
 - Get plumbing code in (it's pretty much ready to go now)
 - Core functionality for the auth plugin with 100% test coverage
 - Examples
 - Documentation
 - Typings
 - Release package

**Comment by mcollina** [comment]
I recommend to get a _really basic version_ of all the above and ship it (minus typing).

**Comment by jonnydgreen** [comment]
Cool, makes sense! I will crack on with that asap :)

**Comment by jonnydgreen** [comment]
Apologies for the slow progress for the second half of last week - I was on holiday - I'm back this week :)
