### ISSUE TITLE
Subscription authentication

### ISSUE THREAD

**Issue by vinicius-ronconi** [mercurius-js/auth#127]
I'm using the directive mode to perform some authentication rules and it works as expected for Queries and Mutations, but for Subscriptions, the `authContext` is never triggered. 

After the pubSub publishes a message, the applyPolicy is triggered and the authentication logic can block the content to be published, but that means we ma have a number of unauthorized connections consuming resources. Is that the expected behaviour? Is there any configuration I can use to avoid these connections?

During my tests, I'm using the following configuration for the mercuriusAuth. It is the same as described in the README, just added the log messages.

```
app.register(mercuriusAuth, {
  authContext (context) {
    context.log.debug('authContext triggered');
    return {
      identity: context.reply.request.headers['x-user']
    }
  },
  async applyPolicy (authDirectiveAST, parent, args, context, info) {
    context.log.debug('applyPolicy triggered');
    return context.auth.identity === 'admin'
  },
  authDirective: 'auth'
})
```

When I check my logs, I can see only the `applyPolicy triggered` message.

**Comment by jmagnuss** [comment]
This appears to be the crux of it - subscriptions don't follow the normal execution flow and the `preExecution` hook that mercurius-auth uses will never be triggered on subscriptions....
![CleanShot 2023-12-02 at 8  47 45@2x](https://github.com/mercurius-js/auth/assets/618676/003983f3-7861-4606-9d41-f18fa91927f5)
I think the authContext should hook to both `preExecution` and `preSubscriptionExecution`

**Comment by vinicius-ronconi** [comment]
@jmagnuss , great suggestion! I tested it here and it works like a charm.

There is another approach that could be used: when we register Mercurius on the fastify app, we can use the `subscription.verifyClient` to validate the token:

```
app.register(mercurius, {
  schema,
  resolvers,
  context: myBuildContext,
  subscription: {
    emitter: redis({host: '127.0.0.1', port: 6379}),
    verifyClient: (info, next) => {
      if (info.req.headers['x-fastify-header'] !== 'fastify is awesome !') {
        return next(false) // the connection is not allowed
      }
      next(true) // the connection is allowed
    }
  },
});
```

I'm closing this ticket since we have different ways to solve the problem I raised.
