### ISSUE TITLE
Getting "FastifyError [Error]: fastify-plugin: mercurius-auth - expected '4.x' fastify version, '5.0.0' is installed" error when trying to upgrade to fastify v5.0.0

### ISSUE THREAD

**Issue by rahulpol10** [mercurius-js/auth#130]
I am trying to upgrade fastify version in my project from 4.28.1 to 5.0.0 but I am getting the following error:

throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
 FastifyError [Error]: fastify-plugin: mercurius-auth - expected '4.x' fastify version, '5.0.0' is installed
     at Object.checkVersion (node_modules/fastify/lib/pluginUtils.js:125:11)
     at Object.registerPlugin (node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (node_modules/fastify/lib/pluginOverride.js:28:57)
     at Boot._loadPlugin (node_modules/avvio/boot.js:425:25)
     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
   statusCode: 500
 }
 
I  got this error after updating fastify version requirement in the package.json. The latest version of mercurius-auth is 5.0.0 which supports fastify 4.28.1
Any idea when you will upgrade mercurius-auth to support fastify 5.x

**Comment by jonnydgreen** [comment]
Hi, thanks for getting in touch! I plan on getting this released to support Fastify 5.x this week :)

**Comment by rahulpol10** [comment]
any update on this?

**Comment by jonnydgreen** [comment]
@rahulpol10  v6.0.0 should be released now with this fix - let us know if you run into any issues!
