### ISSUE TITLE
auth directive on type not being processed, federated service

### ISSUE THREAD

**Issue by dragonfriend0013** [mercurius-js/auth#24]
I have multiple federated services, and each schema looks similar to the following:

```
directive @auth(requires: String!) on OBJECT | FIELD_DEFINITION
extend type Query {
  """
  Provide information about an account's balances
  """
  inqAcctAvail(
    clientId: Int!
    acctId: String!
    suffix: Int
  ): AcctAvail @auth(requires: "inqAcctAvail")
}

type AcctAvail @auth(requires: "inqAcctAvail") @key(fields: "clientId acctId suffix") {
  clientId: Int
  acctId: String
  suffix: Int

  """
  Available money from AAS realtime auth system
  """
  availMoney: Float

  """
  Available cash from AAS realtime auth system
  """
  availCash: Float
}
```

My auth function looks like so:

```
app.register(mercuriusAuth, {
    authContext(context) {
      const {
        reply: {
          request: {
            headers,
          },
        },
      } = context;
      if (headers.introspect === 'true') {
        return {};
      }
      if (!headers['gql-auth']) {
        throw new Error('Not authorized');
      }
      return {
        identity: JSON.parse(context.reply.request.headers['gql-auth']),
      };
    },
    async applyPolicy(
      authDirectiveAST,
      source,
      { clientId: argClientId },
      {
        auth: {
          identity,
        },
      },
    ) {
      const findArg = (arg, ast) => {
        let result;
        ast.arguments.forEach((a) => {
          if (a.kind === 'Argument'
            && a.name.value === arg) {
            result = a.value.value;
          }
        });
        return result;
      };
      const requires = findArg('requires', authDirectiveAST);
      let srcClientId;
      if (source) {
        srcClientId = source.clientId;
      }
      const clientId = argClientId || srcClientId;
      if (!requires
        || (
          process.env.NODE_ENV !== 'production'
          && identity.roles.includes(':admin')
        )) {
        return true;
      }
      if (!identity.roles.includes(`${pad(clientId, 4)}:${requires}`)) {
        throw new Error('User does not have access');
      }
      return true;
    },
    authDirective: 'auth',
  });
```

When testing my inqAcctAvail query, the auth works perfectly.  However when testing the AcctAvail type through an entity call, the applyPolicy is not being triggered through my test, thus it is failing.

Test: 

```
test('should throw error, entity not authorized', async (t) => {
  const variables = {
    representations: [
      {
        __typename: 'AcctAvail',
        clientId: 5555,
        acctId: '10000000001',
        suffix: 0,
      },
    ],
  };
  const query = '
      query EntitiesQuery($representations: [_Any!]!) {
        _entities(representations: $representations) {
          __typename
          ... on AcctAvail {
            clientId
            suffix
            acctId
          }
        }
      }';
  const res = await app.inject({
    method: 'POST',
    url: '/graphql',
    body: {
      query,
      variables,
    },
    headers: {
      'gql-auth': JSON.stringify({
        roles: ['9999:fail'],
      }),
    },
  });
  const response = JSON.parse(res.body);
  t.equal(response.errors ? response.errors[0] : null, 'User does not have access');
  t.end();
});
```

**Comment by jonnydgreen** [comment]
Good catch - if I've understood it correctly, I think authorising like this is not currently supported and we'll need to resolve this issue - just to make doubly sure about this, could you format your examples so I can understand your scenario a bit better as I'm struggling to read the test and auth registration? :)

**Comment by dragonfriend0013** [comment]
i updated the post.  weird how my mac does that when i insert code

**Comment by jonnydgreen** [comment]
Cool thanks for doing that, I understand the test a lot better now! :) Just so I've got the complete picture, can I ask why you are testing through an internal entity call? Do you have another service that references this type and does this protect correctly (e.g. something like this: https://github.com/mercurius-js/auth/blob/main/test/basic-gateway.js#L112)?

**Comment by dragonfriend0013** [comment]
I have designed the federated services so that owning service is responsible for its own authentication.  This way the calling service does not know of/what auth the called service is using.  Makes it easier to implement additional services without having to know the specifics of the called services auth methods.

**Comment by jonnydgreen** [comment]
Apologies for the late reply, I completely missed this! Cool thanks for the clarification, I'll need to take a closer look, but it looks like we need to account for this use-case. Would you be interested in submitting a PR?

**Comment by dragonfriend0013** [comment]
With my current workload, i will try to get a pr available, but it could take a while.

**Comment by jonnydgreen** [comment]
Awesome! Happy to help if you need anything :)

**Comment by dragonfriend0013** [comment]
@jonnydgreen have you had a chance to review my PR?

**Comment by jonnydgreen** [comment]
Sorry, not yet - I'll review this evening (europe time :)) - thanks for submitting!
