### ISSUE TITLE
Failed authorization throws Http 500

### ISSUE THREAD

**Issue by artecoop** [mercurius-js/auth#32]
Hello everyone!

When this plugin returns an error, of any type, it uses HTTP 500 as status code. In this case Apollo (for Angular) treat it as networkError instead of graphQlErrors, making it difficult to handle.
I'm doing something wrong?

**Comment by mcollina** [comment]
Can you create a small example to reproduce? Thanks

**Comment by artecoop** [comment]
Ciao Matteo,
here you are my minimum reproducible repo 
https://github.com/artecoop/mercurius-auth-issue

toggle `@auth(requires: administrator)` inside src/modules/business/schema.ts to view the error.

I've tested it with postman

Note: cert keys are throwaway so don't worry

**Comment by mcollina** [comment]
I think you might want to control the statusCode for the response. If you do not set it it's 500.

```js
const err = new mercurius.ErrorWithProps('UNAUTHORIZED');
err.statusCode = 200
throw err
```

I think we might want to add an optional `statusCode` property in https://github.com/mercurius-js/mercurius/blob/b671de31178395ea53f2ea39c19cc3f8d80be8eb/lib/errors.js#L7 to better control this.

**Comment by mcollina** [comment]
We should probably document this somewhere. Would you like to send a PR?

**Comment by artecoop** [comment]
I saw you merged my changes into the docs and they're now live. However, the changes it refers are not yet released in mercurius...

**Comment by artecoop** [comment]
I saw you guys published mercurius@8.6.0 that brings what discussed here.
However, my code still returns 500 as http status

```ts
 app.register(mercuriusAuth, {
            authContext(context) {
                return {
                    authorization: context.reply.request.headers.authorization
                };
            },
            async applyPolicy(authDirectiveAST, _parent, _args, context) {
                if (!context.auth?.authorization) {
                    const err = new mercurius.ErrorWithProps('UNAUTHENTICATED');
                    err.statusCode = 200
                    throw err
                }

                const { roles } = context.app.jwt.verify(context.auth.authorization);

                if (authDirectiveAST.arguments && authDirectiveAST.arguments.length > 0) {
                    const role = authDirectiveAST.arguments[0].value as EnumValueNode;
                    return roles.includes(role.value);
                }

                const err = new mercurius.ErrorWithProps('UNAUTHORIZED');
                err.statusCode = 200
                throw err
            },
            authDirective: 'auth'
        });
```

Is worth nothing to say that using
```ts
throw new mercurius.ErrorWithProps('UNAUTHORIZED', undefined, 200);
```

does not change the result.

```
"fastify": "3.22.0"
"fastify-jwt": "3.1.0"
"mercurius": "8.6.0"
"mercurius-auth": "1.2.1"
```

**Comment by jonnydgreen** [comment]
@artecoop the work to fix this has been merged and released in mercurius v9.0.0, can you confirm that it is working as expected? https://github.com/mercurius-js/mercurius/issues/599

**Comment by artecoop** [comment]
@jonnydgreen yes, i can confim it work as expected now. Sorry for being late to answer. I'll close this issue as resolved

**Comment by jonnydgreen** [comment]
no worries at all! And thanks
