### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sharmapukar217** [mercurius-js/auth#5]
Will there be any support to use with typescript i.e: proper typings?

**Comment by jonnydgreen** [comment]
Yep, I think that's a great idea! I was planning on adding support for this very soon, unless you'd like to open a PR for this?

**Comment by sharmapukar217** [comment]
I'm working on it .. I'm not so good at these but for me I have made it work. would you like to see it?

**Comment by jonnydgreen** [comment]
Awesome and yes please, could you submit a draft PR?

**Comment by sharmapukar217** [comment]
> Awesome and yes please, could you submit a draft PR?

can i send you the code first? I mean through email or something?

**Comment by jonnydgreen** [comment]
> can i send you the code first? I mean through email or something?

I would prefer a draft PR from your fork - we can then iterate on your suggestion in the PR. This is so we can provide easy and early feedback within the repo and crucially, other members can access the code and provide feedback as well!

**Comment by sharmapukar217** [comment]
ok i'll draft a PR
